menu:
    Posts: /
    Archives: /archives/
    #生活: /categories/live/
    #摄影: /categories/film/
    #关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
yungentie: 
disqus: tpscash 
duoshuo: 


# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016

